local DMW = DMW
DMW.Rotations.WARLOCK = {}
local Warlock = DMW.Rotations.WARLOCK
local UI = DMW.UI

function Warlock.Settings()
    UI.HUD.Options = {
        [1] = {
            Curse = {
                [1] = {Text = "Curse |cFF00FF00Enabled", Tooltip = ""},
                [2] = {Text = "Curse |cffff0000Disabled", Tooltip = ""}
            }
        },
        [2] = {
            MultiDot = {
                [1] = {Text = "Multi-DOt |cFF00FF00Enabled", Tooltip = ""},
                [2] = {Text = "Curse |cffff0000Disabled", Tooltip = ""}
            }
        },
   }				

  UI.AddHeader("Warlock .:|:. General")
    UI.AddDropdown("Rotation", "Rotation mode | Auto = Automatically switch to Raiding in raids, PvP while pvping and Leveling/Solo when < 60lvl or farming items.", {"Auto", "Raiding", "Leveling/Solo", "PvP", "Testing"}, 1, 1)
    UI.AddDropdown("Curse", nil, {"Disabled", "Curse of Agony", "Curse of Shadow", "Curse of the Elements", "Curse of Recklessness", "Curse of Weakness", "Curse of Tongues", "Curse of Doom"}, 2, 1)
   -- UI.AddDropdown("Pause Key", "Key to hold to pause the rotation", {"L-CTRL", "L-SHIFT", "L-ALT", "R-CTRL", "R-SHIFT", "R-ALT"}, 2, 1)
    UI.AddDropdown("Shadow Bolt", "Select Shadow Bolt mode", {"Disabled", "Always", "Only Nightfall"}, 2)
    UI.AddRange("Shadow Bolt Mana", "Minimum mana pct to cast Shadow Bolt", 0, 100, 1, 35)
    UI.AddToggle("Searing Pain", "Use Searing Pain when Shadow Bolt is disabled or not castable", false)
   UI.AddBlank()
    UI.AddToggle("Debug", "Enable printing of spells casting in chat for debug reasons. ", false)
   
   UI.AddBlank()
  UI.AddHeader("Warlock .:|:. Shadowburn")
    UI.AddToggle("Shadowburn", "Shadowburn execute on max shards", false, true)
    UI.AddDropdown("Shadowburn Modifiers", nil, {"Disabled", "2+ DMG Modifiers", "3+ DMG Modifiers"}, 1, true, 0.5)
   UI.AddBlank()
    UI.AddRange("Shadowburn TTD", "TTD to use Shadowburn", 0, 15, 1, 3)
    UI.AddRange("Shadowburn HP", "Health percent to use Shadowburn", 0, 15, 1, 3)
   
   UI.AddBlank()
  UI.AddHeader("Warlock .:|:. Drain Soul/Shards")
    UI.AddToggle("Drain Soul Snipe", "Try to auto snipe enemies with drain soul, useful for shard farming or Improved Drain Soul talent", false)
    UI.AddRange("Drain Soul TTD", "TTD to use Shadowburn", 0, 15, 1, 3)
    UI.AddRange("Drain Soul HP", "Health percent to use Shadowburn", 0, 15, 1, 3)
   UI.AddBlank()
    UI.AddToggle("Stop DS At Max Shards", "Stop using Drain Soul when max shards reached", false)
    UI.AddToggle("Auto Delete Shards", "Activate automatic deletion of shards from bags, set max below", false)
    UI.AddRange("Max Shards", "Control max number of shards in bag", 0, 30, 1, 4)

   UI.AddBlank()
  UI.AddHeader("Warlock .:|:. Life Tap")
    UI.AddToggle("Life Tap", "Enables the use of life tap.", true,1)
    UI.AddRange("Life Tap Mana", "Mana pct to use Life Tap", 0, 100, 1, 15)
    UI.AddRange("Life Tap HP", "Minimum player hp to use Life Tap", 0, 100, 1, 45)
   UI.AddBlank()
    UI.AddToggle("Aggro Life Tap", "Do not Life Tap if you have aggro", false, true,1)
    UI.AddToggle("Life Tap Full HP", "Life tap at full health.", true)
    UI.AddToggle("Life Tap OOC", "Activate Life Tap usage outside combat", true)
    
   UI.AddBlank()
  UI.AddHeader("Warlock .:|:. Pet ")   
    UI.AddDropdown("Pet", nil, {"Disabled", "Succubus", "Voidwalker", "Imp", "Felhunter"}, 2, true)
    UI.AddToggle("Fel Domination", "Auto cast Fel Domination for instant pet summons", true,1) 

    UI.AddToggle("Safe Life Tap", "Do not Life Tap if you have aggro", false, true)
   UI.AddBlank()
    UI.AddToggle("Stop DS At Max Shards", "Stop using Drain Soul when max shards reached", false)
    UI.AddToggle("Auto Delete Shards", "Activate automatic deletion of shards from bags, set max below", false)
    UI.AddRange("Max Shards", "Control max number of shards in bag", 0, 30, 1, 4)
    UI.AddToggle("Debug", "Enable printing of spells casting in chat for debug reasons. ", false)
    
    
 UI.AddHeader("Warlock .:|:. Pet ")   
    UI.AddDropdown("Pet", nil, {"Disabled", "Succubus", "Voidwalker", "Imp", "Felhunter"}, 1, true)
    UI.AddToggle("Imp When No Shards", "Summon Imp when you are out of soul shards.", true, 1) 
    UI.AddToggle("Fel Domination", "Auto cast Fel Domination for instant pet summons", true) 
    UI.AddToggle("Demonic Sacrifice", "Auto cast demonic sacrifice to get its passive buff", true)
   UI.AddBlank()
    UI.AddToggle("Auto Pet Attack", "Auto cast Fel Domination for instant pet summons", true,1) 
    UI.AddToggle("Pet Follow HP%", "Percentage of your pet's HP when it auto follows you", true)
    UI.AddToggle("Imp When No Shards", "Summon Imp when you are out of soul shards.", true) 

   UI.AddBlank()
 UI.AddHeader("Warlock .:|:. DPS Items")
    UI.AddDropdown("Trinket", "Select a trink you would like the rotation to auto use.", { "Disabled", "Talisman of Epheremal Power", "Zandalarian Hero Charm", "Restrained Essence of Sapphiron", "Draconic Infused Emblem", "Burst of Knowledge", "Eye of Moam", "Mar'li's Eye"}, 2, 1, true)
    UI.AddRange("Trinket TTD", "Minimum Time to Die of unit before using damage trinket.", 5, 60, 1, 15, false, 1, 1)
    UI.AddRange("Trinket Mana %", "Minimum mana before using damage trinket.", 5, 100, 1, 45, false, 1, 1)
   UI.AddBlank()
    UI.AddDropdown("Major Rejuvenation Potion", "Use a Major Tejuvenation Potion during raid", {"Disabled", "Major Rejuvenation Potion"}, 2, 1)
    UI.AddRange("Rejuvenation HP %", "Player's health percent to use the selected rune. ", 5, 100, 1, 45, false, 1, 1)
    UI.AddRange("Rejuvenation Mana %", "Use the selected mana potion when mana reaches this percent.", 5, 100, 1, 15, false, 1, 1)
   UI.AddBlank()
    UI.AddDropdown("Mana Potion", "Select a mana potion to use during raid", {"Disabled", "Major Mana Potion", "Superior Mana Potion", "Combat Mana Potion"}, 2, 1)
    UI.AddRange("Potion Mana %", "Use the potion when mana reaches this percent.", 5, 100, 1, 15, false, 1, 1)
   UI.AddBlank()
    UI.AddDropdown("Mana Rune", "Select a rune to use during raid", {"Disabled", "Demonic Rune", "Dark Rune"}, 2, 1)	
    UI.AddRange("Rune Mana %", "Mana percent to use the selected rune. ", 5, 100, 1, 15, false, 1, 1)
    UI.AddRange("Rune HP %", "Player's health percent to use the selected rune. ", 5, 100, 1, 45, false, 1, 1)
   UI.AddBlank()
    UI.AddToggle("Excess Demonic Runes", "Use demonic runes more frequently if you have a lot of them in your bag", true, 1) 
    UI.AddRange("Demonic Rune Count", "Demonic Run amount to have > than to use more frequently", 5, 250, 1, 50, false, 1, 1)
    UI.AddRange("Demonic Rune Mana %", "Demonic Run percent to use the selected rune", 5, 100, 1, 20, false, 1, 1)
   UI.AddBlank()
    UI.AddToggle("Night Dragons Breath", "Use Night Dragon's Breath for mana gain", false, 1) 
    UI.AddRange("Night Dragon Mana %", "Mana percent to use Night Dragon's Breath", 5, 100, 1, 15, false, 1, 1)
   UI.AddBlank()
    UI.AddHeader("Warlock .:|:. Area of Effect")
    UI.AddToggle("Hellfire" ,"Toggle the use of the hellfire AoE ability", true, 1)
   UI.AddBlank()
    UI.AddRange("Hellfire Enemy Count", "Amount of enemies near you in order to hellfire.", 0, 10, 1, 3)
    UI.AddRange("Hellfire TTD", "The minimum time to die of the enemies to hellfire", 0, 15, 1, 2)
    UI.AddRange("Hellfire HP", "Minimum HP Percent to cast hellfire.", 0, 100, 1, 50)
   UI.AddBlank()
    UI.AddToggle("Rain of Fire" ,"Toggle the use of the Rain of Fire AoE ability at range.", true, 1)
   UI.AddBlank()
    UI.AddRange("RoF Mana", "Minimum Mana Percent to cast Rain of Fire.", 0, 100, 1, 30)
    UI.AddRange("RoF Enemy Count", "Amount of enemies near you in order to Rain of Fire.", 0, 10, 1, 4)
    UI.AddRange("RoF TTD", "The minimum time to die of the enemies to Rain of Fire", 0, 10, 1, 2)
   
UI.AddTab("Dots")
 UI.AddHeader("Warlock .:|:. DoTs")
    --UI.AddToggle("Manual Multi-Dot", "Toggle the use of manual multi-dotting, the bot will only multi-dot targets you select/mouseover", true,1)
    UI.AddRange("Multidot Limit", "Max number of units to dot", 1, 10, 1, 3)
   UI.AddBlank()
    UI.AddToggle("Amplify Curse", "Use Amplify Curse when using CDs", true,1)
    UI.AddToggle("Cycle Curse", "Spread Curse to all enemies", true,1) 
    UI.AddRange("Curse TTD", "TTD to use curses.", 0, 10, 1, 3)
   UI.AddBlank()
    UI.AddToggle("Corruption", "Toggle the use of the DoT Corruption on/off", true)
    UI.AddToggle("Corruption Snapshot", "Refhresh corruption right before on use spell damage trinkets buff's expire on boss fights", true,1)
    UI.AddToggle("Cycle Corruption", "Spread Corruption to all enemies", false,1)
    UI.AddRange("Corruption TTD", "TTD to use corruption", 0, 15, 1, 3)
    UI.AddToggle("Multi Dot Corruption Rank 1", "Use rank 1 corruption for multi dotting", false)
   UI.AddBlank()
    UI.AddToggle("Cycle Immolate", "Spread Immolate to all enemies", false,1)
    UI.AddToggle("Immolate", nil, true)
    UI.AddRange("Immolate TTD", "TTD to use corruption.", 0, 15, 1, 3)
   UI.AddBlank()
    UI.AddToggle("Cycle Siphon Life", "Spread Siphon Life to all enemies", false,1)
    UI.AddToggle("Siphon Life", nil, true)
    UI.AddRange("Siphon TTD", "TTD to use corruption.", 0, 18, 1, 3)

UI.AddTab("Defenses")
 UI.AddHeader("Warlock .:|:. Defenses")
    UI.AddToggle("Fear Bonus Mobs", "Auto fear non target enemies when solo", false)
    UI.AddToggle("Fear Solo Farming", "Auto fear target, useful for higher level chars using voidwalker", false)
   UI.AddBlank()
    UI.AddDropdown("Death Coil Mode", "Select the mode you want Death Coil to use.", { "Disabled", "Defense", "Interrupt", "Fear", "Burst"}, 2, 1, true)
    UI.AddRange("Death Coil HP", nil, 0, 100, 1, 23)
   UI.AddBlank()
    UI.AddToggle("Healthstone", nil, true)
    UI.AddRange("Healthstone HP", nil, 0, 100, 1, 30)
   UI.AddBlank()
    UI.AddToggle("Health Potion", nil, true)
    UI.AddRange("Health Potion HP", nil, 0, 100, 1, 15)
   UI.AddBlank()
    UI.AddToggle("Limited Invulnerability Potion", "Use limited invulnerability potion if you gain threat inside of a raid group.", false)
    UI.AddRange("LIP HP", nil, 0, 100, 1, 90) 
   UI.AddBlank()
    UI.AddToggle("Drain Life", nil, true)
    UI.AddRange("Drain Life HP", nil, 0, 100, 1, 25)
    UI.AddToggle("Sacrifice", "Activate Sacrifice", true)
    UI.AddRange("Sacrifice HP", "Player HP to cast Sacrifice", 0, 100, 1, 20)
    UI.AddToggle("Health Funnel", "Activate Health Funnel, will only use if player HP above 60", false)
    UI.AddRange("Health Funnel HP", "Pet HP to cast Health Funnel", 0, 100, 1, 20)
   UI.AddBlank()
    UI.AddToggle("Luffa", "Auto use luffa trinket", true)
    UI.AddToggle("Shadow Ward", "Auto cast shadow ward when targeting priest or warlock players", true)

UI.AddTab("Utility")
 UI.AddHeader("Warlock .:|:. Utility")
    UI.AddToggle("Auto Racials", nil, true) 
    UI.AddRange("War Stomp Enemy Count", "Control max number of shards in bag", 0, 3, 1, 1)
    UI.AddToggle("Demon Armor", "Auto buff with Demon Skin/Armor", true)
   UI.AddBlank()
    UI.AddToggle("Swiftness Potion", "Enable the use of swiftness potions if you are 30 yards away and in combat with an enemy.", false)
    UI.AddToggle("Trash Buffs", "Auto buff yourself with Unending Breath/Detect Invisibility for Garr", false)
   UI.AddBlank()
    UI.AddToggle("Create Healthstone", nil, true)
    UI.AddToggle("Create Soulstone", nil, false)
    UI.AddToggle("Soulstone Player", "Auto Soulstone on player outside instances", true)
   UI.AddBlank()
    UI.AddToggle("Drain Soul Snipe", "Try to auto snipe enemies with drain soul, useful for shard farming or Improved Drain Soul talent", false)
    UI.AddToggle("Stop DS At Max Shards", "Stop using Drain Soul when max shards reached", false)
    UI.AddToggle("Auto Delete Shards", "Activate automatic deletion of shards from bags, set max below", false)
    UI.AddRange("Max Shards", "Control max number of shards in bag", 0, 30, 1, 4)

UI.AddTab("Leveling")
 UI.AddHeader("Warlock .:|:. Leveling")
    UI.AddToggle("Auto Target", "Auto target units when in combat and target dead/missing", false)
    UI.AddToggle("Auto Target Quest Units", nil, false)
    UI.AddToggle("Wand", "Enable the usage of Wands", true, true)
    UI.AddToggle("Auto Attack In Melee", "Use auto attack (melee, low level)", false)
   UI.AddBlank() 
    UI.AddToggle("Drain Life Filler", "Use Drain Life as filler over wanding, use this for drain tanking", false)
    UI.AddRange("Drain Life Filler HP", "Player HP to start using drain life over wanding", 0, 100, 1, 80)
    UI.AddToggle("Dark Pact", nil, false)
    UI.AddToggle("Dark Pact OOC", "Activate Life Tap usage outside combat", false)
    UI.AddRange("Dark Pact Mana", "Mana pct to use Dark Pact", 0, 100, 1, 60)
    UI.AddRange("Dark Pact Pet Mana", "Pet mana pct to use Dark Pact", 0, 100, 1, 35)
    --
    DMW.Helpers.Rotation.CastingCheck = false
end
